"use client";
import {FormEvent,useState} from "react";
import Link from "next/link";
const base=()=>process.env.NEXT_PUBLIC_API_URL || "http://localhost:8000/api/v1";
export default function ForgotPassword(){
 const [institutionCode,setInstitutionCode]=useState("GAINT"),[email,setEmail]=useState(""),[otp,setOtp]=useState(""),[password,setPassword]=useState(""),[confirm,setConfirm]=useState(""),[step,setStep]=useState<"request"|"reset"|"done">("request"),[message,setMessage]=useState(""),[loading,setLoading]=useState(false);
 async function requestCode(e:FormEvent){e.preventDefault();setLoading(true);setMessage("");try{const r=await fetch(base()+"/auth/forgot-password",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({institution_code:institutionCode,email})});const j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.detail||"Unable to request reset code");setStep("reset");setMessage("If this account exists, a 6-digit code has been sent to its email.");}catch(e){setMessage(e instanceof Error?e.message:"Request failed")}finally{setLoading(false)}}
 async function reset(e:FormEvent){e.preventDefault();setMessage("");if(password!==confirm){setMessage("Passwords do not match.");return}setLoading(true);try{const r=await fetch(base()+"/auth/reset-password",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({institution_code:institutionCode,email,otp,new_password:password})});const j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.detail||"Reset failed");setStep("done");setMessage("Password updated. You can now sign in.");}catch(e){setMessage(e instanceof Error?e.message:"Reset failed")}finally{setLoading(false)}}
 return <main className="auth-shell"><form className="auth-card" onSubmit={step==="request"?requestCode:reset}><div className="brand-mark">GA</div><p className="eyebrow">GAINT ACADEMY</p><h1>Reset password</h1>
 {step==="done"?<><p className="muted">{message}</p><Link href="/login">Return to sign in</Link></>:<><p className="muted">{step==="request"?"Enter your institution and account email.":"Enter the 6-digit code and choose a new password."}</p><label>Institution code<input value={institutionCode} onChange={e=>setInstitutionCode(e.target.value.toUpperCase())} required disabled={step==="reset"}/></label><label>Email<input type="email" value={email} onChange={e=>setEmail(e.target.value)} required disabled={step==="reset"}/></label>{step==="reset"&&<><label>Reset code<input inputMode="numeric" pattern="[0-9]{6}" maxLength={6} value={otp} onChange={e=>setOtp(e.target.value.replace(/\D/g,""))} required/></label><label>New password<input type="password" minLength={10} value={password} onChange={e=>setPassword(e.target.value)} required autoComplete="new-password"/></label><label>Confirm password<input type="password" minLength={10} value={confirm} onChange={e=>setConfirm(e.target.value)} required autoComplete="new-password"/></label></>}{message&&<p className={message.startsWith("If ")?"muted":"error"}>{message}</p>}<button disabled={loading}>{loading?"Please wait…":step==="request"?"Send reset code":"Reset password"}</button>{step==="reset"&&<button type="button" className="secondary" onClick={()=>{setStep("request");setOtp("");setMessage("")}}>Start again</button>}<p className="secure-note"><Link href="/login">Back to sign in</Link></p></>}</form></main>
}